# Generated by Django 4.2.4 on 2023-08-19 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsabilityQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('easy_to_find', models.PositiveIntegerField()),
                ('well_organised', models.PositiveIntegerField()),
                ('easy_to_read', models.PositiveIntegerField()),
                ('comfortable_language', models.PositiveIntegerField()),
                ('no_left_right_scroll', models.PositiveIntegerField()),
                ('know_where_i_am', models.PositiveIntegerField()),
                ('useful_cues_links', models.PositiveIntegerField()),
                ('easy_to_move_around', models.PositiveIntegerField()),
                ('well_maintained_links', models.PositiveIntegerField()),
                ('not_many_new_windows', models.PositiveIntegerField()),
                ('standard_placement_links', models.PositiveIntegerField()),
                ('attractive_design', models.PositiveIntegerField()),
                ('comfortable_colors', models.PositiveIntegerField()),
                ('no_irritating_features', models.PositiveIntegerField()),
                ('consistent_look', models.PositiveIntegerField()),
                ('easy_to_learn', models.PositiveIntegerField()),
                ('fast_downloads', models.PositiveIntegerField()),
                ('distinguish_links', models.PositiveIntegerField()),
                ('expected_responses', models.PositiveIntegerField()),
                ('efficient_use', models.PositiveIntegerField()),
                ('clear_useful_messages', models.PositiveIntegerField()),
            ],
        ),
    ]
