# Generated by Django 4.2.2 on 2023-08-02 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consentform',
            old_name='confirmed',
            new_name='signed',
        ),
    ]
