# Generated by Django 4.2.4 on 2023-08-12 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentgroup',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
