# Generated by Django 4.2.4 on 2023-08-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_usabilityquestionnaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_name', models.CharField(max_length=100)),
                ('quiz_type', models.CharField(max_length=50)),
                ('final_score', models.PositiveIntegerField()),
                ('individual_answers', models.JSONField()),
                ('confidence_levels', models.JSONField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
