# Generated by Django 4.2.4 on 2023-08-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_treatmentgroup_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='link',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
