# Generated by Django 4.2.2 on 2023-08-02 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0002_rename_confirmed_consentform_signed'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentform',
            name='date',
            field=models.DateField(default='2023-01-01'),
        ),
    ]
