# Generated by Django 4.2.4 on 2023-08-21 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0003_participantresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ParticipantResponse',
        ),
    ]
