# Generated by Django 4.2.2 on 2023-08-03 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0003_consentform_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='consent_form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='basicapp.consentform'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='treatment_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='basicapp.treatmentgroup'),
        ),
    ]
