# Generated by Django 4.2.4 on 2023-08-21 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0004_delete_participantresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentform',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='age',
            field=models.IntegerField(choices=[['1', '18-24'], ['2', '25-29'], ['3', '30-34'], ['4', '35-39'], ['5', '40-44'], ['6', '45-49'], ['7', '50-54'], ['8', '55-59'], ['9', '60-64'], ['10', '65-69'], ['11', '70-74'], ['12', '75-79'], ['13', '80-84'], ['14', 'Age 85 and over']]),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='education',
            field=models.CharField(choices=[['1', 'Primary School'], ['2', 'Secondary School'], ['3', 'Higher or secondary or further education (A-levels, BTEC, professional certificate.)'], ['4', 'University, of equivalent'], ['5', 'Post-graduate degree'], ['6', 'Other'], ['7', 'Prefer not to say']], max_length=100),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='ethnicity',
            field=models.CharField(choices=[('Asian or Asian British', (('1', 'Indian'), ('2', 'Pakistani'), ('3', 'Bangladeshi'), ('4', 'Chinese'), ('5', 'Any other Asian background'))), ('Black or Black British', (('1', 'Caribbean'), ('2', 'African'), ('3', 'Any other Black, Black British or Caribbean background'))), ('Mixed or multiple ethnic groups', (('1', 'White and Black Caribbean'), ('2', 'White and Black African'), ('3', 'White and Asian'), ('4', 'Any other Mixed or multiple ethnic background'))), ('White', (('1', 'English, Welsh, Scottish, Northern Irish or British'), ('2', 'Irish'), ('3', 'Gypsy or Irish Traveller'), ('4', 'Roma'), ('5', 'Any other White background'))), ('Other ethnic group', (('1', 'Arab'), ('2', 'Any other ethnic group')))], max_length=50),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='gender',
            field=models.CharField(choices=[['1', 'Male'], ['2', 'Female'], ['3', 'Non-Binary'], ['4', 'Other'], ['5', 'Prefer not to say']], max_length=10),
        ),
        migrations.AlterField(
            model_name='demographic',
            name='occupation',
            field=models.CharField(choices=[['1', 'Managers, Directors and Senior Officials'], ['2', 'Professional Occupations'], ['3', 'Associate Professional and Technical Occupations'], ['4', 'Administrative and Secretarial Occupations'], ['5', 'Skilled Trades Occupations'], ['6', 'Caring, Leisure and Other Service Occupations'], ['7', 'Sales and Customer Service Occupations'], ['8', 'Process, Plant and Machine Operatives'], ['9', 'Elementary Occupations'], ['10', 'Retired'], ['11', 'Full Time Student'], ['12', 'Not in Employment'], ['13', 'Other']], max_length=100),
        ),
    ]
