# Generated by Django 4.2.4 on 2023-08-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0004_tutorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
