# Generated by Django 4.2.2 on 2023-08-10 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0004_alter_participant_consent_form_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.IntegerField()),
                ('selected_option', models.CharField(max_length=10)),
                ('confidence', models.PositiveIntegerField(choices=[(1, 'Not at all'), (2, 'Somewhat'), (3, 'Neutral'), (4, 'Confident'), (5, 'Extremely confident')])),
                ('reasoning', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='responses',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='responses',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='claim',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
        migrations.RemoveField(
            model_name='question',
            name='source',
        ),
        migrations.AddField(
            model_name='question',
            name='authenticity',
            field=models.CharField(choices=[('real', 'Real'), ('fake', 'Fake')], default='fake', max_length=10),
        ),
        migrations.AddField(
            model_name='question',
            name='details',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='summary',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='treatmentgroup',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='participant',
            name='treatment_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='basicapp.treatmentgroup'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(null=True, upload_to='question_images/'),
        ),
        migrations.AlterField(
            model_name='treatmentgroup',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.DeleteModel(
            name='Responses',
        ),
        migrations.AddField(
            model_name='participantanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicapp.question'),
        ),
    ]
