# Generated by Django 4.2.2 on 2023-08-10 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0005_participantanswer_remove_responses_participant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantanswer',
            name='participant_id',
            field=models.IntegerField(null=True),
        ),
    ]
