# Generated by Django 4.2.2 on 2023-08-10 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0006_alter_participantanswer_participant_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('image', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('authenticity', models.CharField(max_length=10)),
                ('explanation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Responses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_chosen', models.CharField(max_length=10)),
                ('score', models.IntegerField()),
                ('confidence_level', models.IntegerField()),
                ('reasoning', models.TextField(blank=True)),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicapp.participant')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basicapp.quizquestion')),
            ],
        ),
        migrations.DeleteModel(
            name='ParticipantAnswer',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
