# Generated by Django 4.2.4 on 2023-08-13 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0006_tutorial_treatment_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
