# Generated by Django 4.2.4 on 2023-08-13 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0007_alter_tutorial_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentgroup',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
